export const CHANGE_POPUP = 'CHANGE_POPUP';
export const CHANGE_ISLOGIN = 'CHANGE_ISLOGIN';
export const CHANGE_USER = 'CHANGE_USER';
export const CHANGE_LOADING = 'CHANGE_LOADING';
export const SET_NOTES = 'SET_NOTES';